name: Publish Docker image
# found here https://docs.github.com/en/actions/language-and-framework-guides/publishing-docker-images
on: [push]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: qristof
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: qristof/qseoksso
          tag_with_ref: true
